// استيراد من firebase.js
import {
    db,
    collection,
    addDoc,
    doc,
    getDoc,
    getDocs,
    updateDoc,
    deleteDoc,
    setDoc,
    getCollection,
    loadProducts,
    addProduct,
    deleteProduct,
    loadOrders,
    addOrder,
    updateOrder,
    deleteOrder,
    loadCustomers,
    addCustomer,
    updateCustomer,
    deleteCustomer,
    getSettings,
    setSettings,
    getOrdersWithCustomers
} from './firebase.js';

// إعادة تصدير كل الدوال لاستخدامها في الصفحات الأخرى
export {
    db,
    collection,
    addDoc,
    doc,
    getDoc,
    getDocs,
    updateDoc,
    deleteDoc,
    setDoc,
    getCollection,
    loadProducts,
    addProduct,
    deleteProduct,
    loadOrders,
    addOrder,
    updateOrder,
    deleteOrder,
    loadCustomers,
    addCustomer,
    updateCustomer,
    deleteCustomer,
    getSettings,
    setSettings,
    getOrdersWithCustomers
};
