// استيراد من firebase.js
import {
    db,
    collection,
    addDoc,
    doc,
    getDoc,
    getDocs,
    updateDoc,
    deleteDoc,
    setDoc,
    deleteField,
    getCollection,
    loadProducts,
    addProduct,
    updateProduct,
    deleteProduct,
    updateProductStock,
    loadCustomers,
    addCustomer,
    updateCustomer,
    deleteCustomer,
    loadOrders,
    addOrder,
    updateOrder,
    deleteOrder,
    getOrdersWithDetails,
    getSettings,
    setSettings
} from './firebase.js';

// إعادة تصدير كل شيء
export {
    db,
    collection,
    addDoc,
    doc,
    getDoc,
    getDocs,
    updateDoc,
    deleteDoc,
    setDoc,
    deleteField,
    getCollection,
    loadProducts,
    addProduct,
    updateProduct,
    deleteProduct,
    updateProductStock,
    loadCustomers,
    addCustomer,
    updateCustomer,
    deleteCustomer,
    loadOrders,
    addOrder,
    updateOrder,
    deleteOrder,
    getOrdersWithDetails,
    getSettings,
    setSettings
};
